name: time-tracker-frontend-react-ci
run-name: \[${{ github.actor }}\] - Time Tracker React Frontend CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test -- --watchAll=false